apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    run: mongo
    
spec:
  containers:
  - image: sayali063/newimage0:new_version
    name: mongo
    ports:
    - containerPort: 3000
  dnsPolicy: ClusterFirst
  restartPolicy: Always